### ISSUE TITLE
Графический движок v3

### ISSUE THREAD

**Issue by whitequartz** [bmstu-iu9/utp2019-2-2d-game#11]
Как его использовать?
**Инициализация**
```JavaScript
const r = new Engine();
r.init([image, background, playerImage, interface], [waterAnimation, lavaAnimation]);
```
* `image` - это объект `Image`
* `background` - это изображение с фоном объекта `Image`
* `playerImage` - это изображение с игроком объекта `Image`
* `interface` - это изображение с интерфейсом объекта `Image`
* `waterAnimation` - это изображение с анимацией воды
* `lavaAnimation` - это изображение с анимацией лавы

Пример использования типа Image:
```JavaScript
const image = new Image();
image.src = 'image.png';
image.onload = () => {
	...
}
```
Изображения должны находится в виде текстурного атласа, которые будут с помощью текстурных координат частично использования.
Изображения должны быть квадратными и использовать размер степени двойки.

Настройка (должна быть вызвана перед созданием объектов **обязательно**):
```JavaScript
.settings(size, widthChunk, heightChunk, lightOfChunks)
```
* `size` - размер блоков
* `widthChunk` - ширина чанков
* `heightChunk` - высота чанков
* `lightOfChunks` - массив коэффициентов освещения слоёв (на данный момент не используется)

Создание объекта:
```JavaScript
.createObjects(arrayOfObjects)
```
* `arrayOfChunk` - массив/объект таких ассоциативных массивов: `{'id': id, 'a': [x1, y1], 'b': [x2, y2]}`
  * `id` - id блока
  * `x1`, `y1` - координаты левого верхнего угла на текстуре `[0..1]`
  * `x2`, `y2` - координаты нижнего правого угла на текстуре `[0..1]`

Инициализация анимаций:
```JavaScript
.initAnimations(array)
```
* `array` - это массив таких массивов: `[function, id]`
  * `function` - функция, которая должна проверять, подходит ли этот блок под анимацию
  * `id` - затычка для анимации

**Отрисовка**
Отрисовка чанка в буфер кадров (создание/обновление):
```JavaScript
.drawChunk(x, y, blocksOfChunk, lightChunk)
```
* `x`, `y` - координаты чанка
* `blocksOfChunk` - массив чанков блоков
* `lightChunk` - чанк освещения

Удаление чанка из буфера кадров:
```JavaScript
.deleteChunk(x, y)
```
* `x`, `y` - координаты чанка

Отрисовка:
```JavaScript
.render(xc, yc, xp, yp, scale, time, deltaTime, lightOfDay, lightOfPlayer, slicePlayer, rotatePlayer, dynamicLight)
```
* `xc`, `yc` - координаты камеры
* `xp`, `yp` - координаты игрока
* `scale` - масштаб экрана
* `time` - время прошедшее с начала работы игры (или с какого-то определённого момента, главное, что оно не обнуляется во время игры
* `deltaTime` - время прошедшее между отрисовкой предыдущего и текущего кадра в секундах
* `lightOfDay` - освещение фона `[0..1]`
* `lightOfPlayer` - освещение игрового персонажа `[0..1]`
* `slicePlayer` - `1` = игрок перед передним слоем, `2` = игрок за передним слоем
* `rotatePlayer` - если значение положительное, то игровой персонаж повёрнут направо, если отрицательное, то игровой персонаж повёрнут налево
* `dynamicLight` - массив, состоящий из двух элементов, где первый элемент задаёт диаметр динамического освещения, а второй параметр задаёт максимальное освещение в центральной точке (в месте, где находится игровой персонаж)

**Погода**
Плавный запуск дождя:
```JavaScript
.startRain()
```

Плавная остановка дождя:
```JavaScript
.stopRain()
```
Возвращает примерное время в секундах до окончания дождя.

**Отрисовка объектов**
Создать текстуру:
```JavaScript
.createTexture(image, width, height)
```
* `image` - изображение (должно быть квадратным)
* `width`, `height` - ширина и высота изображения. Изображение будет растянуто под указанную ширину и высоту.

Исходное изображение должно быть квадратным! Вызывать желательно только 1 раз на каждое изображение при инициализации!

Получить размер экрана в пикселях:
```JavaScript
.getCanvasSize()
```
* возвращает массив из двух элементов (ширина и высота экрана)

Отправить объекты на отрисовку:
```JavaScript
.drawObjects(texture, array)
```
* `texture` - текстура, полученная из .createTexture
* `array` - массив, состоящий из объектов вида:
* `{'pa': [paX, paY], 'pb': [pbX, pbY], 'ta': [taX, taY], 'tb': [tbX, tbY]}`
  * `pa` - нижний левый угол позиции объекта
  * `pb` - верхний правый угол позиции объекта
  * `ta` - нижний левый угол текстурных координат
  * `tb` - верхний правый угол текстурных координат

Отправить индикаторы на отрисовку:
```JavaScript
.drawProgressBars(texture0, texture1, array)
```
* `texture0` - текстура, полученная из .createTexture для заполненного значения
* `texture1` - текстура, полученная из .createTexture для пустого значения
* `array` - массив, состоящий из объектов вида:
* `{'pa': [paX, paY], 'pb': [pbX, pbY], 'ta': [taX, taY], 'tb': [tbX, tbY]}`
  * `pa` - нижний левый угол позиции объекта
  * `pb` - верхний правый угол позиции объекта
  * `ta` - нижний левый угол текстурных координат
  * `tb` - верхний правый угол текстурных координат
  * `hor` - `true` = горизонтальный индикатор, `false` = вертикальный индикатор
  * `status` - заполненность индикатора `[0..1]`

Вызывать можно только после .render!

- [x] Основа игрового движка и движение камеры
- [x] Отрисовка фона
- [ ] Улучшенная работа с фоном **(требуется нарисовать фон #108)**
- [ ] Оптимизация отрисовки (#37)
- [x] Работа с чанками
- [x] Работа с камерой в абсолютных координатах
- [x] Полноценная работа с отрисовкой персонажа (в т.ч. анимации) (#68)
- [x] Добавление буфера кадров для оптимизации отрисовки одинаковых объектов
- [x] Добавление мягкого освещения (#39)
- [ ] Возможность добавления движущихся предметов с отрисовкой (сущности)
- [ ] Анимации разрушения блоков
- [ ] Визуализация погоды (#57)
- [x] Отрисовка интерфейса (#32)
- [x] Третий слой (#95)
- [x] Отображение выбранного предмета инвентаря в руке (#68)
- [x] Динамическое освещение (например, для факелов)

**Comment by whitequartz** [comment]
Добавил возможность работы с отрисовкой интерфейса и фона

**Comment by Mazdaywik** [comment]
Код желательно выделять тремя обратными кавычками, в первой строке после кавычек указываем язык программирования:

    ```JavaScript
    const image = new Image();
    image.src = 'image.png';
    image.onload = () => {
      ...
    }
    ```
Тогда он будет выделяться как листинг кода
```JavaScript
const image = new Image();
image.src = 'image.png';
image.onload = () => {
  ...
}
```

Названия переменных, функций, классов в тексте желательно окружать окружать кавычками:

    * `image` - это объект `Image`;

отобразится как

* `image` - это объект `Image`;

В тексте выше я разукрасил.

**Comment by Mitbus** [comment]
Обнаружил несколько проблемных моментов:
- фон не двигается по вертикали
- при долгом движении влево фон смазывается
- на одноцветных текстурах блоков видно, что задний фон просвечивает, если блоки не накладываются, а стоят впритык

**Comment by whitequartz** [comment]
Полностью изменил работу с движком. Пример смотрите в моей ветке.
Теперь данные принимаются в виде массива чанков.
Работа с камерой будет изменена.
Фон временно отключён.
Интерфейс не работает.

**Comment by Mitbus** [comment]
Документация устарела. Следует заменить ее актуальной перед добавлением в master

**Comment by whitequartz** [comment]
Обновил документацию на вторую версию графического движка. Добавил пример

**Comment by Mazdaywik** [comment]
Вложенные списки оформляются так:
```Markdown
* пункт
* пункт
  * подпункт
  * подпункт
* пункт
  * подпункт
    * подподпункт
* пункт
```
* пункт
* пункт
  * подпункт
  * подпункт
* пункт
  * подпункт
    * подподпункт
* пункт

(поправил в документации)

**Comment by whitequartz** [comment]
Добавлен счётчик fps. Для использования вставить в цикл отрисовки:
```JavaScript
fpsUpdate();
```

**Comment by whitequartz** [comment]
Обновлена документация в связи с добавлением отрисовки игрока

**Comment by whitequartz** [comment]
Практически полностью организован переход к 3 версии движка
Что нового:
* Значительно увеличено количество кадров в секунду (FPS) в связи с использованием буфера кадров
* Исправлены некоторые недочёты
* ~~Добавлены новые баги:~~
  * [x] ~~Не отображается задний фон блоков~~
  * [x] ~~Временно отключен фон~~
  * [x] ~~Отрисованный мир не меняется после установки блоков и смены времени суток~~

**Comment by whitequartz** [comment]
Документация будет обновлена в ближайшем будущем.
Пример будет удалён из-за ненадобности.

**Comment by Mitbus** [comment]
При использовании фреймбуфера встает проблема: необходимо уметь отслеживать изменения блоков в чанках. Эффективно сделать это на этапе рендера не получается, поэтому давайте перед каждое переприсваивание `gameArea.map` заменим на функцию, которая помимо присваивания будет проверять, в какой чанк установлен блок, и если этот чанк лежит в буфере, то будет добавлять его в массив измененных блоков. Тогда имея для каждого чанка такой массив, мы можем эффективно принимать решение о перерисовке всего чанка\ его изменении\неизменении(#91).

**Comment by whitequartz** [comment]
Обновлена документация. Примеров больше не будет.

**Comment by whitequartz** [comment]
Обновлена документация для отрисовки объектов (интерфейса)

**Comment by whitequartz** [comment]
Задачи для оптимизации отрисовки (#37):
Переделать методы:
- [ ] constructor & createProgram - сделать откат к автоматическому линкеру (линкер знает что делает, в отличие от меня 😄)
- [ ] createObjects - ID хранятся очень неудачно. Впоследствии в drawChunk из-за этого происходит лишняя нагрузка.
- [ ] drawChunk - избавиться от передачи лишних данных на GPU с помощью ANGLE_instanced_arrays. Перенести подсчёт ID в createObjects
- [ ] render - попытаться разбить на части. Попытаться избавиться от передачи лишних данных на GPU с помощью ANGLE_instanced_arrays. Исправить дождь

**Comment by whitequartz** [comment]
Исправлено мягкое (плавное) освещение. Теперь оно выглядит немного лучше

**Comment by whitequartz** [comment]
Исправлено множество небольших багов. В основном не происходил учёт зума и scale (cameraScale)

**Comment by whitequartz** [comment]
* В воде теперь игрок отрисовывается в ней, а не поверх неё.
* Вода теперь прозрачная.
* Анимации жидкости: воды и лавы (для демонстрации они двигаются по синусоиде).
* Неполные блоки жидкости с правильным отображением стоящих под ними блоками жидкости.
