### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Shaniser** [bmstu-iu9/utp2019-2-2d-game#4]
Основные задачи (невыполненные в порядке приоритета):

- [ ] Добавление новых возможностей в функционал движка (#11, #39, #68)
- [ ] Детальная работа с объектами игрового мира (#69)
- [x] Анимации игрока
- [x] Интерфейс (#32, #71)
- [x] Полноценная поддержка 2-го слоя
- [x] Предметы в инвентаре и взаимодействие (#66, #67)
- [x] Сохранения (#76)
- [x] Освещённость (#39)
- [x] Механика ломания и установки блоков (#38, #62)
- [x] Выбрать, с какими блоками мы будем иметь дело (#10)
- [x] Написание основы игрового мира (блоки как объекты с нужными параметрами и т.п.) (#9)
- [x] Архитектура проекта (#13)
- [x] Визуализация и создание графического движка (#11) (отрисовка игрока, привязка блоков к их расположению на экране, также какие-либо текстуры, движение камеры, фон)
- [x] Генерация мира (#12)
- [x] Методы работы с камерой (#27)
- [x] Управление (ввод с клавы (#7), мыши (#8), определение на какой блок наведен курсор (по координатам и размерам)

Второстепенные задачи:

- [ ] Погода (#57, #11)
- [ ] Улучшенная генерация мира (#33)
- [ ] Оптимизация (#37)

Далее возможно: #71

**Comment by Mazdaywik** [comment]
Теперь можно для отдельных пунктов создавать подзадачи и добавлять сюда.

**Comment by Shaniser** [comment]
А как отметить, что я, например, взялся за задачу, но ещё не выполнил?

**Comment by Mazdaywik** [comment]
Я для примера создал подзадачу для первого пункта.

Assignees ставите на себя, там можете ставить метку «In progress» (создал эту метку специально для вас). Набор меток можно редактировать.
