### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Mitbus** [bmstu-iu9/utp2019-2-2d-game#86]
Описание ошибок, найденных в проекте:
- [x] В редких случаях игрок может попасть на самый край блока, при этом его движение в сторону от блока невозможно, считается, что он каждый момент в воздухе => нельзя прыгать. Такое чувство, что где-то стоит <= вместо < (#16)
- [x] При сохранении и перезагрузке на вершинах кубов появляются точки (#76)
- [x] За прозрачными объектами ничего не рисуется (#37)
- [x] Если собрать блок в инвентарь, взять его в руку, то предметы такого же типа будут уничтожаться слишком быстро (#66 )
- [x] Игрок появляется в блоках (#33 )
- [x] Камера продолжает движение по инерции при свернутой вкладке
- [x] Не сохраняются большие миры (#76)
- [x] При зависаниях в воздухе (даже при прыжке с небольшой высоты) наносится много урона (#87)
- [x] При активном изменении мира нельзя сохраняться (#87)
- [x] Некорректное растекание лавы (#87)
- [x] По непонятным причинам (иногда) при загрузке сохранений появляются блоки со всеми `undefined` полями
- [x] Иногда происходит резкий скачек при изменении суток
- [x] Артефакты света
- [x] Находясь на 2 слое не видно второго слоя за первым
- [x] При изменении пропорции разрешения меняется скорость дождя
- [x] При сохранении теряется скорость (upd. В мире нет инерции)
- [x] Метод `placeBlock` в `gameArea`: происходит путаница строковых и числовых значений id блоков при использовании
- [x] Вода перестала растекаться
- [x] При генерации под деревьями трава
- [x] Дюп травы при ломании блока земли
- [x] Нельзя плавать в текучей воде
- [x] Удаление части древесины после ломания листвы
- [x] Сохранения не работают, если открыто 2 окна
- [x] Некорректно ломаются деревья, которые граничат с концом мира.
- [x] Если пытаться ставить блоки дерева в воздухе, но при этом они сбоку будут соприкасаться с каким-либо другим блоком, то данный блок из инвентаря исчезает, но при этом в мире не появляется.
- [x] При ломании дерева не всегда собирается точное количество блоков, которое оно содержало.
- [x] В ветке интерфейс не работают сохранения: на каком-то этапе сохраняется анонимная функция, к которой потом нельзя обратиться
- [x] Нет коллизии с золотом
- [x] Люки и двери не ставятся друг на друга (interface)
- [x] После сохранения недосчитанные симуляции забывают досчитаться, например, зависает песок
- [x] Дюп блоков при их движении при сохранении
- [x] Из инвентаря невозможно удалить сложные предметы: кирки, лопаты и т.п.
- [x] Уничтожение листвы не зависит от `alwaysGoodDestroy`
- [x] Дождь не зависит от `cameraScale` (`preprocessing.js`)
- [x] Ломание и установка блоков не учитывают `cameraScale`
- [x] При зуме с работающей `cameraScale` появляются артефакты (#91)
    - [x] При увеличении падает разрешение текстур и теней
    - [x] При отдалении съезжает задний фон
- [x] Полупрозрачное свечение вокруг игрока на главном слое не учитывают `cameraScale`
- [x] Если предмет кончился, то если его добыть вновь, он встанет обрано в слот быстрого интерфейса, но пока его в инвентаре 1 шт. его нельзя поставить
- [x] Если ломать факел не рукой (ломал каменной киркой), то он будет уничтожаться (не попадает в инвентарь)
- [x] Дождь следует за игроком\камерой? по блокам (капли должны оставаться на своих местах вне зависимости от движения игрока) (#57)
- [x] Зум счетчика fps
- [x] Скорость дождя зависит от скорости игрока (#57)
- [x] При падении лава превращается в воду и летят ошибки
- [x] Не сохраняется стамина и дыхание
- [x] После смены режима сглаживания появились белые полосы
- [x] Нет проверки на спавн в дереве
- [x] Листва зависает при сохранении
- [x] Скорость падения листвы зависит от фпс
- [x] В Yandex Browser не работает правый клик мыши (ПКМ в Яндексе вызывает другое событие - вызов контекстного меню)
- [ ] Визуально после смерти с постоянным уроном (например, под водой) полоска хп восполняется и заново начинает убывать, а только потом происходит смерть
- [ ] С зажатой shift и ПКМ в mozilla вызывается контекстное меню вместе с установкой блоков
- [ ] Через неактивную для клика часть интерфейса проходят клики
- [ ] При некоторых разрешениях экрана некоторые части интерфейса съезжают. Например, при 800х600 предметы в слотах сдвинуты, 1280х720 между кнопками инвентаря появляются щели и т.п.
- [ ] Окно крафта накладывается на полосы здоровья, стамины и пр.
- [ ] Под некоторыми углами в левом верхнем углу нельзя взаимодействовать с блоками
- [ ] Некорректно обрабатывается zoom в браузере safari (правильно работает, только при стандартном зуме)
- [ ] В Firefox Developer Edition не работают сохранения.
- [ ] Верхний блок земли в пещерах генерируется без травы

**Comment by Mitbus** [comment]
Стоит ли запрос на исправление помечать как bugs?)

**Comment by Shaniser** [comment]
> Стоит ли запрос на исправление помечать как bugs?)

Думаю норм

**Comment by whitequartz** [comment]
В некоторых случаях (в момент подвисания), если прыгнуть в воду (даже с небольшой высоты), то можно улететь высоко в небо.
Вот видео, которое демонстрирует данный баг: https://www.youtube.com/watch?v=FkXiyV1bo9A

**Comment by Mitbus** [comment]
Исправлен баг с точками. Дело было в JSON, теперь передается копия объекта. Решение в ветке issue-77

**Comment by pirosveta** [comment]
Если пытаться ставить блоки дерева в воздухе, но при этом они сбоку будут соприкасаться с каким-либо другим блоком, то он из инвентаря исчезает, но при этом в мире не появляется.

**Comment by pirosveta** [comment]
- Некорректно ломаются деревья, которые граничат с концом мира.
- Если пытаться ставить блоки дерева в воздухе, но при этом они сбоку будут соприкасаться с каким-либо другим блоком, то данный блок из инвентаря исчезает, но при этом в мире не появляется.
- При попытке сломать один блок листвы - разрушается также и какое-то количество соседней листвы, а также блоки дерева.
- При ломании дерева не всегда собирается точное количество блоков, которое оно содержало.

**Comment by pirosveta** [comment]
Иногда, возможно после долгого нахождения в игре, появляется белый экран и происходит перезагрузка.

Upd: как выяснилось, это происходит из-за смерти персонажа

**Comment by whitequartz** [comment]
> Иногда, возможно после долгого нахождения в игре, появляется белый экран и происходит перезагрузка.

Скорее всего смерть игрового персонажа из-за падения или утопления

**Comment by pirosveta** [comment]
> > Иногда, возможно после долгого нахождения в игре, появляется белый экран и происходит перезагрузка.
> 
> Скорее всего смерть игрового персонажа из-за падения или утопления

При этом происходит следующая ошибка:
![image](https://user-images.githubusercontent.com/52463878/61582745-1c29b080-ab48-11e9-8706-1864c928e17c.png)

**Comment by pirosveta** [comment]
- Если сломать дерево, то все блоки дерева исчезают, однако листва остается на месте;
- Не знаю баг это или нет, но при переходе игроком на задний план - становится возможным ходить по поверхности воды;
- Когда игрок не может пройти мимо дерева, он может пройти мимо листвы этого дерева, то есть листва остается всегда как бы на "заднем плане".

**Comment by pirosveta** [comment]
Из инвентаря не только нельзя удалить сложные предметы (кирки, лопаты и т.п.), но и нельзя даже убрать в сундук. При попытке это сделать - происходит зависание навсегда.

**Comment by Shaniser** [comment]
@pirosveta
1) не знаю, свежие изменения
2) игрок ходит по песку
3) листва не имеет коллизии (как ходить по листикам?)

**Comment by Shaniser** [comment]
@pirosveta это уже интереснее

**Comment by Shaniser** [comment]
> Из инвентаря не только нельзя удалить сложные предметы (кирки, лопаты и т.п.), но и нельзя даже убрать в сундук. При попытке это сделать - происходит зависание навсегда.

Исправил, проверяй

**Comment by Mitbus** [comment]
ТАм одна и та же ошибка вызывается - предмет удалиться не может. А насчет 1 и 3 - cейчас починю, хотя как по- мне без коллизии листвы прикольнее

**Comment by Shaniser** [comment]
@Mitbus 
Я против коллизии
Особенно, если ты сможешь сделать падающую листву

**Comment by Mitbus** [comment]
Коллизии нет, листочки падают. `develop`

**Comment by Shaniser** [comment]
> Коллизии нет, листочки падают. `develop`

Работает отлично! Может сделать, чтоб они не все исчезали, и на земле треть или половина оставалась? Как думаешь?

**Comment by Mitbus** [comment]
Сейчас сделал так: падающая листва падает все время, а которая останется - до первого препятствия. Потенциально это может принести проблемы: если листочки будут долго жить, то запекшиеся листочки ведут себя иначе. По сути можно исправить, если есть необходимость, но это усложнит логику

**Comment by Shaniser** [comment]
Саженцы будем делать? 
Или ну их?

**Comment by Mitbus** [comment]
А почему бы и нет? Деревья генерировать умеем

**Comment by Shaniser** [comment]
Тогда @pirosveta нужно разобраться с тем, как делать это в процессе игры

**Comment by pirosveta** [comment]
Может будет лучше, если при попытке собрать упавшую листву, будет уничтожаться только разрушаемый блок и те, что стоят на нём? Сейчас же, при уничтожении блока листвы, ломаются и все его соседи.

**Comment by Mitbus** [comment]
Будет проблематично отличать упавшую листву от листы на дереве, а такое поведение на дереве выглядит весьма странно

**Comment by whitequartz** [comment]
> Будет проблематично отличать упавшую листву от листы на дереве, а такое поведение на дереве выглядит весьма странно

Пусть листва на дереве имеет какой-то ID. А при падении листвы будет использоваться другой ID.
А также можно добавить параметр data у определённых блоков.

**Comment by Mitbus** [comment]
Я предлагал такое решение для блоков, которые должны себя вести по особенному только при генерации (стволы деревьев, листва, мб что-то еще), но его заругали

**Comment by Shaniser** [comment]
Блоки с перенасыщенностью красного, твой косяк, @Mitbus
Ждём хотфикс

**Comment by Mitbus** [comment]
Починил баг с яндексом, но тк там изменен порядок вызова событий, нельзя зажать ПКМ, чтобы ставить много блоков (mousedown вызывается при отпускании для ПКМ)

**Comment by whitequartz** [comment]
Firefox Quantum 69.0 (64-битный)
не работают сохранения
